name: Daily scraper of CISA KEV json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Scrape CISA KEV
        run: |
          curl -L -o known_exploited_vulnerabilities.json \
          -H "User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36" \
          https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "AboutCode Automation"
          git config user.email "automation@aboutcode.org"
          git add -A
          timestamp=$(date -u)
          git commit -m "$(echo -e "Update KEV: $timestamp\n\nSigned-off-by: AboutCode Automation <automation@aboutcode.org>")" || exit 0
          git push
